# Generated by Django 4.2.29 on 2026-04-07 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('interests', models.JSONField(blank=True, default=list)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('modified', 'User Modified'), ('failed', 'Generation Failed')], default='generating', max_length=12)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlanBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('wake_up', 'Wake Up'), ('meal', 'Meal'), ('activity', 'Activity'), ('child_care', 'Child Care'), ('travel', 'Travel/Commute'), ('work', 'Work'), ('study', 'Study'), ('exercise', 'Exercise'), ('free_time', 'Free Time'), ('errand', 'Errand'), ('sleep', 'Wind Down / Sleep')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveIntegerField()),
                ('is_fixed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.child')),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='planner.dayplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('homemaker', 'Homemaker'), ('parent', 'Homemaker with Kids'), ('student', 'Student'), ('professional', 'Professional')], default='parent', max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('wake_time', models.TimeField(default='06:00')),
                ('sleep_time', models.TimeField(default='22:00')),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('cuisine_preferences', models.JSONField(blank=True, default=list)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('personal', 'Personal'), ('appointment', 'Appointment'), ('school_drop', 'School Drop-off'), ('school_pick', 'School Pick-up'), ('child_activity', 'Child Activity/Class'), ('class', 'Class/Lecture'), ('study', 'Study Session'), ('exam', 'Exam'), ('assignment_due', 'Assignment Due'), ('work_shift', 'Work Shift'), ('meeting', 'Meeting')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('travel_time_minutes', models.PositiveIntegerField(default=0)),
                ('recurrence', models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekdays', 'Weekdays (Mon–Fri)'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='none', max_length=10)),
                ('recurrence_days', models.JSONField(blank=True, default=list, help_text='For custom recurrence: [0,2,4] = Mon,Wed,Fri')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.child')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='planner.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('leave_time', 'Time to Leave'), ('prep_meal', 'Start Meal Prep'), ('general', 'General Reminder'), ('pickup', 'School Pickup'), ('assignment', 'Assignment Due')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('remind_at', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.planblock')),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.scheduleevent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='planner.userprofile')),
            ],
            options={
                'ordering': ['remind_at'],
            },
        ),
        migrations.AddField(
            model_name='planblock',
            name='linked_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.scheduleevent'),
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prep_time_minutes', models.PositiveIntegerField(default=0)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planner.dayplan')),
            ],
            options={
                'ordering': ['meal_type'],
            },
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_lists', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('profile', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('produce', 'Fruits & Vegetables'), ('dairy', 'Dairy'), ('grains', 'Grains & Cereals'), ('protein', 'Protein'), ('spices', 'Spices & Condiments'), ('snacks', 'Snacks'), ('other', 'Other')], default='other', max_length=10)),
                ('checked', models.BooleanField(default=False)),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.grocerylist')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dayplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='planner.userprofile'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planner.userprofile'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='planner.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='planner.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('profile', 'date')},
        ),
    ]
