# Generated by Django 4.2.29 on 2026-04-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='breakfast_types',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["South Indian", "English", "Continental"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='breakfast_weight',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_cuisines',
            field=models.TextField(blank=True, help_text='Free text for specific cuisines not in the list'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dinner_types',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Soup & bread", "Salad", "Light curry"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dinner_weight',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exclusions',
            field=models.JSONField(blank=True, default=list, help_text='Things to exclude from day plan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grocery_day',
            field=models.CharField(blank=True, default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lunch_types',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Rice based", "Roti based", "One pot"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lunch_weight',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='heavy', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='snack_preferences',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Fruits", "Homemade", "Baked"]'),
        ),
    ]
