# Generated by Django 4.2.29 on 2026-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_userprofile_breakfast_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='planning_modules',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["meals", "grocery", "exercise", "kids_activities"]'),
        ),
    ]
