# Generated by Django 4.2.29 on 2026-04-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_userprofile_planning_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='module_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Per-module preferences: {"exercise": {"types": ["Gym"], "time": "morning"}}'),
        ),
    ]
