# Generated by Django 4.2.29 on 2026-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_userprofile_module_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('leave_time', 'Time to Leave'), ('prep_meal', 'Start Meal Prep'), ('general', 'General Reminder'), ('pickup', 'School Pickup'), ('assignment', 'Assignment Due'), ('meeting', 'Meeting Prep'), ('exercise', 'Exercise Time'), ('class', 'Class Starting'), ('study', 'Study Session')], max_length=15),
        ),
    ]
