# Generated by Django 4.2.29 on 2026-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_reminder_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='plan_data',
            field=models.JSONField(blank=True, default=dict, help_text='User-type-specific structured plan JSON'),
        ),
    ]
