# Generated by Django 4.2.29 on 2026-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('homemaker', 'Homemaker'), ('parent', 'Homemaker with Kids'), ('new_mom', 'New Mom (Infant)'), ('working_mom', 'Working Mom'), ('professional', 'Professional')], default='parent', max_length=20),
        ),
    ]
