# Generated by Django 4.2.29 on 2026-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_layout',
            field=models.JSONField(blank=True, default=list, help_text='User-customised dashboard layout: [{"key": "meal_cards", "visible": true, "locked": false}]'),
        ),
    ]
