# Generated by Django 4.2.29 on 2026-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_userprofile_custom_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='family_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of people she cooks for (including herself)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["PCOS", "thyroid", "high protein diet", "iron deficiency"]'),
        ),
    ]
