# Generated by Django 4.2.29 on 2026-04-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_userprofile_family_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=200)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_meals', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'meal_name')},
            },
        ),
    ]
