# Generated by Django 4.2.29 on 2026-04-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_favouritemeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grocery_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
        migrations.CreateModel(
            name='UserPantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='planner.userprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('profile', 'name')},
            },
        ),
    ]
