# Generated by Django 4.2.29 on 2026-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_userprofile_grocery_frequency_userpantryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocerylist',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='grocerylist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
