# Generated by Django 4.2.29 on 2026-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_grocerylist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grocery_day',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
