# Generated by Django 4.2.29 on 2026-04-12 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_alter_userprofile_grocery_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSwapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=10)),
                ('rejected_meal', models.CharField(max_length=200)),
                ('chosen_meal', models.CharField(max_length=200)),
                ('user_request', models.CharField(blank=True, help_text='What the user typed for change requests, empty for swaps', max_length=300)),
                ('day_of_week', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_swap_logs', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
