# Generated by Django 4.2.29 on 2026-04-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_mealswaplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsActivityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('theme', models.CharField(max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_activity_plans', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('profile', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='KidsActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 1=Tuesday … 4=Friday')),
                ('story_title', models.CharField(max_length=300)),
                ('story_text', models.TextField()),
                ('worksheet_topic', models.CharField(max_length=300)),
                ('worksheet_content', models.JSONField(default=dict, help_text='{"questions": [...], "instructions": "..."}')),
                ('coloring_description', models.TextField()),
                ('is_downloaded', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to='planner.child')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planner.kidsactivityplan')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('plan', 'child', 'day_of_week')},
            },
        ),
    ]
