# Generated by Django 4.2.29 on 2026-04-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_kidsactivityplan_kidsactivityday'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsactivityday',
            name='story_emoji',
            field=models.CharField(default='📖', max_length=10),
        ),
        migrations.AddField(
            model_name='kidsactivityday',
            name='story_illustration',
            field=models.TextField(blank=True, help_text='AI-generated illustration description for the story'),
        ),
        migrations.AlterField(
            model_name='kidsactivityday',
            name='coloring_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kidsactivityday',
            name='worksheet_content',
            field=models.JSONField(default=dict, help_text='{"activities": [...]}'),
        ),
    ]
