# Generated by Django 4.2.29 on 2026-04-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_kidsactivityday_story_emoji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseworkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_help_type',
            field=models.CharField(choices=[('self', 'I do everything myself'), ('partial_help', 'I have part-time help'), ('full_maid', 'I have full-time help')], default='self', max_length=15),
        ),
        migrations.CreateModel(
            name='HouseworkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('housework_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.houseworklist')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='houseworklist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housework_lists', to='planner.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='houseworklist',
            unique_together={('profile', 'date')},
        ),
    ]
