# Generated by Django 4.2.29 on 2026-04-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_houseworklist_userprofile_home_help_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseworkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days', models.JSONField(blank=True, default=list, help_text='Weekdays: 0=Mon,1=Tue,2=Wed,3=Thu,4=Fri,5=Sat,6=Sun. Empty=every day.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housework_templates', to='planner.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
