# Generated by Django 4.2.29 on 2026-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_houseworktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='action_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pending_action',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
