# Generated by Django 4.2.29 on 2026-04-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_chatmessage_action_status_chatmessage_pending_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='event_date',
            field=models.DateField(blank=True, help_text='For one-off events: the specific date this event occurs on', null=True),
        ),
    ]
