# Generated by Django 4.2.29 on 2026-04-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_scheduleevent_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseworkTaskDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('was_ai_generated', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housework_deletion_logs', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
