# Generated by Django 4.2.29 on 2026-04-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_houseworktaskdeletionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_section_lists', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('profile', 'section_key', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CustomSectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('section_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.customsectionlist')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomSectionDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=200)),
                ('was_ai_generated', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_section_deletion_logs', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
