# Generated by Django 4.2.29 on 2026-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_customsectionlist_customsectiontask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='baby_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='baby_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='had_csection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_breastfeeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='support_type',
            field=models.CharField(blank=True, choices=[('partner_all_day', 'Partner home all day'), ('partner_after_6', 'Partner home after 6pm'), ('family_visiting', 'Family visiting'), ('health_visitor', 'Health visitor'), ('flying_solo', 'Mostly on my own')], default='', max_length=20),
        ),
    ]
