# Generated by Django 4.2.29 on 2026-04-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_userprofile_baby_date_of_birth_userprofile_baby_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialsCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essentials_checks', to='planner.userprofile')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('profile', 'date', 'item')},
            },
        ),
    ]
