# Generated by Django 4.2.29 on 2026-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_essentialscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='is_user_added',
            field=models.BooleanField(default=False),
        ),
    ]
