# Generated by Django 4.2.29 on 2026-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_groceryitem_is_user_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentialscheck',
            name='added_to_grocery',
            field=models.BooleanField(default=False),
        ),
    ]
