# Generated by Django 4.2.29 on 2026-04-23 09:32

from django.db import migrations, models


def backfill_works_outside_home(apps, schema_editor):
    """Seed works_outside_home for existing rows so their dashboards don't
    regress. Users previously labelled working_mom/professional are the
    only groups where the flag should default to True."""
    UserProfile = apps.get_model('planner', 'UserProfile')
    UserProfile.objects.filter(user_type__in=['working_mom', 'professional']).update(
        works_outside_home=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0027_essentialscheck_added_to_grocery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='works_outside_home',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_works_outside_home, noop_reverse),
    ]
