# Generated by Django 4.2.29 on 2026-04-23 10:13

from django.db import migrations, models


def rebucket_professionals(apps, schema_editor):
    """Any existing user_type='professional' row becomes 'homemaker' — the
    derived-label equivalent for works_outside_home=True with no children.
    Their dashboards get rebuilt separately by the follow-up script."""
    UserProfile = apps.get_model('planner', 'UserProfile')
    UserProfile.objects.filter(user_type='professional').update(
        user_type='homemaker',
        works_outside_home=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0028_userprofile_works_outside_home'),
    ]

    operations = [
        migrations.RunPython(rebucket_professionals, noop_reverse),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('homemaker', 'Homemaker'), ('parent', 'Homemaker with Kids'), ('new_mom', 'New Mom (Infant)'), ('working_mom', 'Working Mom')], default='parent', max_length=20),
        ),
    ]
