# Generated by Django 4.2.29 on 2026-04-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0029_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineMealSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=80, unique=True)),
                ('display_cuisine', models.CharField(max_length=80)),
                ('breakfast', models.JSONField(default=list)),
                ('lunch', models.JSONField(default=list)),
                ('dinner', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
