# Generated by Django 4.2.29 on 2026-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0030_cuisinemealsuggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='activity_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('standard', 'Standard'), ('advanced', 'Advanced'), ('olympiad', 'Olympiad')], default='standard', max_length=20),
        ),
    ]
