# Generated by Django 4.2.29 on 2026-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0031_child_activity_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cooking_responsibility',
            field=models.CharField(choices=[('me', 'I cook'), ('helper', 'Our helper cooks'), ('eat_out', 'We mostly order or eat out')], default='me', max_length=10),
        ),
    ]
