# Generated by Django 4.2.29 on 2026-04-27 12:36
# Hand-edited to use RenameModel + AddField instead of the destructive
# Delete+Create that makemigrations defaults to. Preserves all existing
# Child rows and their FK relationships from PlanBlock / ScheduleEvent /
# KidsActivityDay. Existing rows backfill to role='child' (the default).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0032_userprofile_cooking_responsibility'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='HouseholdMember',
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='parent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='members',
                to='planner.userprofile',
            ),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='role',
            field=models.CharField(
                choices=[
                    ('child', 'Child'),
                    ('partner', 'Partner'),
                    ('grandparent', 'Grandparent'),
                    ('parent', 'Parent'),
                    ('sibling', 'Sibling'),
                    ('helper', 'Helper'),
                    ('roommate', 'Roommate'),
                    ('other', 'Other'),
                ],
                default='child',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='member_dietary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='member_health_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='member_exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
