# Generated by Django 4.2.29 on 2026-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0033_rename_child_householdmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The user's own age — shown on the household members screen.", null=True),
        ),
    ]
