# Generated by Django 4.2.29 on 2026-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0034_add_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secondary_cuisines',
            field=models.JSONField(blank=True, default=list, help_text='Cuisines the household enjoys occasionally (1-2 per week).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spice_level',
            field=models.PositiveSmallIntegerField(default=3, help_text='1=Mild, 2=Light, 3=Medium, 4=Hot, 5=Fire.'),
        ),
    ]
