# Generated by Django 4.2.29 on 2026-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_add_secondary_cuisines_spice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kids_activity_focus',
            field=models.JSONField(blank=True, default=list, help_text='What kinds of activities the household wants for kids (e.g. ["Academic", "Creative", "Outdoor"]).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kids_activity_time_pref',
            field=models.CharField(blank=True, choices=[('after_school', 'After school'), ('weekend', 'Weekend'), ('both', 'Both'), ('', 'No preference')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kids_default_difficulty',
            field=models.CharField(blank=True, default='', help_text='Household-wide default difficulty for kids activities. Per-child overrides on HouseholdMember take precedence.', max_length=20),
        ),
    ]
