# Generated by Django 4.2.29 on 2026-05-02 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0036_add_kids_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayTimelineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_key', models.CharField(max_length=80)),
                ('completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_checks', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-date', 'item_key'],
                'unique_together': {('profile', 'date', 'item_key')},
            },
        ),
    ]
