# Generated by Django 4.2.29 on 2026-06-17 14:28

from django.db import migrations, models

# Dashboard sections that only existed for the work-oriented (working_mom)
# layout, now removed app-wide.
WORK_SECTION_KEYS = {'priorities', 'evening_routine'}


def rebucket_working_moms(apps, schema_editor):
    """Dayo is home-oriented only now. Convert any working_mom profile to
    'parent' (works_outside_home off) and drop the work-only sections from
    their saved dashboard layout so nothing renders a now-missing section.
    Mirrors the earlier 0029 rebucket of the retired 'professional' type.
    """
    UserProfile = apps.get_model('planner', 'UserProfile')
    for profile in UserProfile.objects.all():
        changed = False
        if profile.user_type == 'working_mom':
            profile.user_type = 'parent'
            profile.works_outside_home = False
            changed = True
        if profile.custom_layout:
            cleaned = [s for s in profile.custom_layout if s.get('key') not in WORK_SECTION_KEYS]
            if cleaned != profile.custom_layout:
                profile.custom_layout = cleaned
                changed = True
        if changed:
            profile.save()


def noop_reverse(apps, schema_editor):
    """No reverse — working_mom is gone for good; leave rebucketed rows as-is."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0037_todaytimelinecheck'),
    ]

    operations = [
        migrations.RunPython(rebucket_working_moms, noop_reverse),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('homemaker', 'Homemaker'), ('parent', 'Homemaker with Kids'), ('new_mom', 'New Mom (Infant)')], default='parent', max_length=20),
        ),
    ]
