# Generated by Django 4.2.29 on 2026-10-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0039_cleanup_stale_mealplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('weekly_meals', 'Weekly meal generation'), ('day_plan', 'Day plan generation'), ('grocery', 'Grocery refinement'), ('swap', 'Meal swap'), ('recipe', 'Recipe extraction'), ('chat', 'Chat'), ('other', 'Other')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('prompt_version', models.CharField(blank=True, max_length=12)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='planner.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', '-created_at'], name='planner_gen_service_1b0344_idx')],
            },
        ),
    ]
