# Generated by Django 4.2.29 on 2026-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0040_generationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='cuisine',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='mealswaplog',
            name='chosen_cuisine',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='mealswaplog',
            name='rejected_cuisine',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='mealswaplog',
            name='was_user_request',
            field=models.BooleanField(default=False, help_text='True when the user typed the dish they wanted, False for a tap-to-swap where the model chose the replacement.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dismissed_learned_cuisines',
            field=models.JSONField(blank=True, default=list, help_text='Learned cuisines the user removed — never auto-applied again.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learned_secondary_cuisines',
            field=models.JSONField(blank=True, default=list, help_text='Cuisines inferred from repeated explicit requests (max 2).'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_cuisines',
            field=models.JSONField(blank=True, default=list, help_text='Cuisines the household enjoys occasionally (2-3 per week).'),
        ),
    ]
